modules/models.py
from flask_mysqldb import MySQL

mysql = MySQL()

app.py
from flask import Flask, render_template, flash
from modules.routes import clientes_bp, configure_db
from modules.contactos import contactos_bp
from modules.cotizaciones import cotizaciones_bp, configure_db, descargar_cotizacion
from modules.atajos_teclados import registrar_atajo
from modules.pdf_generator import create_pdf

import keyboard

app = Flask(__name__)
app.register_blueprint(clientes_bp)
app.register_blueprint(contactos_bp)
app.register_blueprint(cotizaciones_bp)

configure_db(app)

# Configurar mensajes flash
app.config['SECRET_KEY'] = 'clave-secreta'

@app.route('/')
def index():
    return render_template('index.html')

# Manejar errores 404
@app.errorhandler(404)
def not_found_error(error):
    return render_template('404.html'), 404

# Manejar errores 500
@app.errorhandler(500)
def internal_error(error):
    flash('Ha ocurrido un error interno en el servidor')
    return render_template('500.html'), 500

if __name__ == '__main__':
    registrar_atajo(app)
    app.run(debug=True)
    keyboard.unhook_all()

modules/routes.py
import sys
sys.path.append('C:\\Users\\Orlando\\Desktop\\ism2\\modules')
from models import mysql
from flask import Blueprint, render_template, request, url_for, redirect, flash
from config import Config

clientes_bp = Blueprint('clientes', __name__)

# Configurar la conexión a MySQL


def configure_db(app):
    app.config.from_object(Config)
    mysql.init_app(app)


# Agregar nuevo cliente
@clientes_bp.route('/clientes', methods=['GET', 'POST'])
def formulario():
    if request.method == 'POST':
        nombre = request.form['nombre']
        direccion = request.form['direccion']
        cp = request.form['cp']
        ciudad = request.form['ciudad']
        telefono = request.form['telefono']
        rfc = request.form['rfc']

        # Insertar datos del formulario en la base de datos
        cursor = mysql.connection.cursor()
        sql = "INSERT INTO clientes (nombre, direccion, cp, ciudad, telefono, rfc) VALUES (%s, %s, %s, %s, %s, %s)"
        val = (nombre, direccion, cp, ciudad, telefono, rfc)
        cursor.execute(sql, val)
        mysql.connection.commit()

        flash('Nuevo cliente agregado')

        return redirect(url_for('clientes.formulario'))

    # Mostrar datos en la tabla
    cursor = mysql.connection.cursor()
    cursor.execute("SELECT * FROM clientes")
    datos = cursor.fetchall()

    return render_template('clientes.html', datos=datos)


# Editar cliente existente
@clientes_bp.route('/editar', methods=['POST'])
def editar():
    id = request.form['id']
    cursor = mysql.connection.cursor()
    cursor.execute("SELECT * FROM clientes WHERE id_cliente=%s", (id,))
    datos = cursor.fetchone()
    return render_template('clientes.html', datos=datos, editar=True)


# Actualizar cliente
@clientes_bp.route('/actualizar', methods=['POST'])
def actualizar():
    id = request.form['id']
    nombre = request.form['nombre']
    direccion = request.form['direccion']
    cp = request.form['cp']
    ciudad = request.form['ciudad']
    telefono = request.form['telefono']
    rfc = request.form['rfc']
    cursor = mysql.connection.cursor()
    cursor.execute("UPDATE clientes SET nombre=%s, direccion=%s, cp=%s, ciudad=%s, telefono=%s, rfc=%s WHERE id_cliente=%s",
                   (nombre, direccion, cp, ciudad, telefono, rfc, id))
    mysql.connection.commit()
    flash('Cliente actualizado')
    return redirect(url_for('clientes.formulario'))


# Eliminar cliente
@clientes_bp.route('/eliminar', methods=['POST'])
def eliminar():
    id = request.form['id']
    cursor = mysql.connection.cursor()
    cursor.execute("DELETE FROM clientes WHERE id_cliente=%s", (id,))
    mysql.connection.commit()
    flash('Cliente eliminado')
    return redirect(url_for('clientes.formulario'))

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="0">
  <title>{% block title %}{% endblock %}</title>
  <!-- Agrega aquí los estilos CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
</head>

<body>
  <!-- Barra de navegación -->


  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('index') }}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('clientes.formulario') }}">Clientes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('contactos.agregar_contacto') }}">Contactos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('cotizaciones.agregar_cotizacion') }}">Cotizaciones</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Contenido de la página -->
  <div class="container">
    <!-- {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class="flash">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %} -->
    {% block content %}{% endblock %}
  </div>

  <!-- Pie de página -->

  <!-- Agrega aquí los scripts JavaScript -->
  <!-- <script src="{{ url_for('static', filename='js/script.js') }}"></script> -->
</body>

</html>

templates/clientes.html
{% extends 'base.html' %}

{% block content %}

<h1>Clientes</h1>
{% include 'formulario_clientes.html' %}
<br><br>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre del Cliente</th>
            <th>Direccion</th>
            <th>CP</th>
            <th>Ciudad</th>
            <th>Telefono</th>
            <th>RFC</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for dato in datos %}
        <tr>
            <td>{{ dato[0] }}</td>
            <td>{{ dato[1] }}</td>
            <td>{{ dato[2] }}</td>
            <td>{{ dato[3] }}</td>
            <td>{{ dato[4] }}</td>
            <td>{{ dato[5] }}</td>
            <td>{{ dato[6] }}</td>
            <td>
                <form action="{{ url_for('clientes.editar') }}" method="POST">
                    <input type="hidden" name="id" value="{{ dato[0] }}">
                    <input type="submit" class="btn btn-primary" value="Editar" {% if editar %}disabled{% endif %}>
                </form>
                <form action="{{ url_for('clientes.eliminar') }}" method="POST">
                    <input type="hidden" name="id" value="{{ dato[0] }}">
                    <input type="submit" class="btn btn-danger" value="Eliminar" {% if editar %}disabled{% endif %}>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock %}

templates/contactos.html
{% extends 'base.html' %}

{% block content %}

<h1>Contactos</h1>
{% include 'formulario_contactos.html' %}

<h2>Lista de contactos</h2>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Contacto</th>
      <th>Correo electrónico</th>
      <th>Cliente</th>
    </tr>
  </thead>
  <tbody>
    {% for contacto in contactos %}
    <tr>
      <td>{{ contacto[0] }}</td>
      <td>{{ contacto[1] }}</td>
      <td>{{ contacto[2] }}</td>
      <td>{{ contacto[3] }}</td>
      <td><button class="btn btn-primary">Editar</button><button class="btn btn-danger">Eliminar</button></td>
    </tr>
    {% endfor %}  </tbody>
</table>



{% endblock %}

templates/cotizaciones.html
{% extends 'base.html' %}

{% block content %}


<div class="position-relative mt-10 mb-5">
    <button type="button" class="btn btn-success position-absolute top-10 start-50 bottom-50 translate-middle btn-lg"
        data-bs-toggle="modal" data-bs-target="#ModalPrincipal" data-bs-whatever="@mdo">
        Agregar Partidas
    </button>
</div>

<div class="modal fade" id="ModalPrincipal" tabindex="-1" aria-labelledby="ModalPrincipalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="ModalPrincipalLabel">Nuevo Presupuesto</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% include 'formulario_cotizaciones.html' %}
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="ModalEditar" tabindex="-1" aria-labelledby="ModalEditarlLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="ModalEditarLabel">Nuevo Presupuesto</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>
<div class="fecha-cot">
    <h2> FECHA: {{ fecha }}</h2>
    <p>COTIZACION: #{{ next_id }}</p>
</div>
<div id="presupuesto">
    <table class="table table-dark table-hover table-bordered border-primary fs-4 top-10 start-0"
        id="cotizaciones-table">
        <thead style="text-align: center;">
            <th style="max-width: 100px;">Partida</th>
            <th>Descripcion</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Importe</th>
            <th>Acciones</th>
        </thead>
        <tbody>
            {% for cotizacion in cotizaciones %}
            <tr>
                <td>{{ loop.index }}</td>
                <td style="text-transform: uppercase;">{{ cotizacion.descripcion }}, material {{ cotizacion.material }}
                </td>
                <td>{{ cotizacion.cantidad }}</td>
                <td>$ {{ '%0.2f' % cotizacion.precio }}</td>
                <td>$ {{ '%0.2f' % cotizacion.importe }}</td>
                <td>
                    <button class="btn btn-primary">Editar</button>
                    <button class="btn btn-danger">Eliminar</button>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">Sub-total:</td>
                <td>$ {{ '%0.2f' % cotizaciones[0].subtotal if cotizaciones else '0.00' }}</td>
            </tr>
            <tr>
                <td colspan="4">IVA (8%):</td>
                <td>$ {{ '%0.2f' % cotizaciones[0].iva if cotizaciones else '0.00' }}</td>
            </tr>
            <tr>
                <td colspan="4">Total:</td>
                <td>$ {{ '%0.2f' % cotizaciones[0].total if cotizaciones else '0.00' }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="select_cliente">
        <select id="cliente-select" name="id_cliente">
            <option value="">Seleccione un cliente</option>
            {% for cliente in clientes %}
            <option value="{{ cliente[0] }}">{{ cliente[1] }}</option>
            {% endfor %}
        </select>

        <ul id="contactos-list"></ul>
    </div>

    <!-- <form id="hidden-form" method="post" action="{{ url_for('cotizaciones.guardar_cotizacion') }}">
        <input type="hidden" name="cliente_id" id="hidden-cliente-id">
    </form> -->
    <input type="hidden" id="hidden-cliente-id" name="cliente_id" value="">

    <button type="button" class="btn btn-primary" id="save-to-db">Guardar en base de datos</button>

    <button type="button" class="btn btn-danger" id="refresh-page" disabled>Refrescar página</button>


</div>
<script src="{{ url_for('static', filename='js/operaciones_mat.js') }}"></script>
<script src="{{ url_for('static', filename='js/mostrar_contactos.js') }}"></script>
<!-- VARIABLE PARA QUE EN EL ARCHIVO JS RECONOZCA LA URL, YA QUE LOS ARCHIVO JS NO SOPORTAN JINJA2 -->
<script>
    var guardarCotizacionUrl = "{{ url_for('cotizaciones.guardar_cotizacion') }}";
</script>
<script src="{{ url_for('static', filename='js/cotizaciones_handler.js') }}"></script>

<script>
    // Crear un nuevo objeto XMLHttpRequest
    // Este es el objeto que usaremos para enviar la solicitud
    // y recibir la respuesta
    var xhr = new XMLHttpRequest();

    // Crear la función de devolución de llamada para ejecutar cada vez que se cambia el estado de la solicitud
    xhr.onreadystatechange = function () {
        if (xhr.readyState === XMLHttpRequest.DONE) {
            if (xhr.status === 200) {
                // Si la cotización se guardó correctamente, descarga el PDF y recarga la página
                var response = JSON.parse(xhr.responseText);

                // Descargar el PDF
                var link = document.createElement("a");
                link.href = "/cotizaciones/descargar_cotizacion/" + response.id_presupuesto;
                link.download = "cotizacion_" + response.id_presupuesto + ".pdf";
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
            }
        }
    };

    // Obtener el formulario
    var form = document.getElementById("cotizacion-form"); // Actualizar el ID del formulario aquí

    // Este objeto nos permite enviar los datos del formulario junto con la solicitud
    var formData = new FormData(form);

    // Asegúrate de que el cliente_id se incluya en los datos enviados
    formData.append("cliente_id", clientId);

    // Enviar una solicitud POST a la ruta de cotización
    xhr.open("POST", "/cotizaciones/cotizar");

    // Enviar la solicitud con los datos del formulario
    xhr.send(formData);
</script>

{% endblock %}

templates/formulario_clientes.html
{% if editar %}
<h2>Editar Cliente</h2>
<form action="{{ url_for('clientes.actualizar') }}" method="POST">
    <input type="hidden" name="id" value="{{ datos[0] }}">
    <label for="nombre">Nombre:</label>
    <input type="text" name="nombre" id="nombre" value="{{ datos[1] }}"><br>
    <label for="direccion">Direccion:</label>
    <input type="text" name="direccion" id="direccion" value="{{ datos[2] }}"><br>
    <label for="cp">CP:</label>
    <input type="text" name="cp" id="cp" value="{{ datos[3] }}"><br>
    <label for="ciudad">Ciudad:</label>
    <input type="text" name="ciudad" id="ciudad" value="{{ datos[4] }}"><br>
    <label for="telefono">Telefono:</label>
    <input type="text" name="telefono" id="telefono" value="{{ datos[5] }}"><br>
    <label for="rfc">R.F.C.:</label>
    <input type="text" name="rfc" id="rfc" value="{{ datos[6] }}"><br>
    <input type="submit" value="Actualizar">
</form>
{% else %}
<h2>Registrar Cliente</h2>
<form action="{{ url_for('clientes.formulario') }}" method="POST">
    <label for="nombre">Nombre:</label>
    <input type="text" name="nombre" id="nombre"><br>
    <label for="direccion">Direccion:</label>
    <input type="text" name="direccion" id="direccion"><br>
    <label for="cp">CP:</label>
    <input type="text" name="cp" id="cp"><br>
    <label for="ciudad">Ciudad:</label>
    <input type="text" name="ciudad" id="ciudad"><br>
    <label for="telefono">Telefono:</label>
    <input type="text" name="telefono" id="telefono"><br>
    <label for="rfc">R.F.C.:</label>
    <input type="text" name="rfc" id="rfc"><br>
    <input type="submit" value="Registrar">
</form>
{% endif %}

templates/formulario_contactos.html
<form action="" method="post">
    <div class="row g-2">
        <div class="col-3">
            <input type="text" name="contacto" id="contacto" class="form-control" placeholder="Contacto"
                aria-label="contacto">
        </div>
        <div class="col-3">
            <input type="text" name="correo" id="correo" class="form-control" placeholder="Correo Electronico"
                aria-label="Correo Electronico">
        </div>
        <div class="col-2">
            <select name="cliente_id" id="cliente_id" class="form-select{% if clientes|length > 3 %}-lg{% endif %}">
                <option value="">Selecciona la empresa del contacto</option>
                {% for cliente in clientes %}
                <option value="{{ cliente[0] }}">{{ cliente[1] }}</option>
                {% endfor %}
            </select>
            
        </div>
        <div>
            <input type="submit" class="btn btn-primary" value="Registrar Contacto">
        </div>

    </div>
</form>

templates/formulario_cotizaciones.html
<form action="{{ url_for('cotizaciones.agregar_cotizacion') }}" method="POST" id="cotizacion-form">
    <div class="mb-1">
        <textarea class="form-control fs-3" name="descripcion"
            placeholder="Descripcion del producto o servicio" id="descripcion" cols="10" rows="6"
            style="text-transform: uppercase;" required></textarea>
    </div>
    <div class="row mb-1">
        <div class="col-sm-4 mb-3 mb-sm-0">
            <div class="card">
                <div class="card-body">
                    <p class="card-text fs-5">F7 (°)</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <p class="card-text fs-5">F8 (#)</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <p class="card-text fs-5">F9 (⌀)</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm mb-1">
        <input type="number" class="form-control fs-3" placeholder="Cantidad" name="cantidad"
            id="cantidad" required>
    </div>
    <div class="col-sm input-group mb-1">
        <div class="input-group-text">$</div>
        <input type="number" class="form-control fs-3" placeholder="Precio" name="p_unitario" id="p_unitario" step="0.01" required>
    </div>
    <div class="col-sm input-group">
        <div class="input-group-text">$</div>
        <input type="number" class="form-control fs-3" placeholder="Importe" name="importe" id="importe" step="0.01" readonly>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="material" id="inox" value="Acero inoxidable"
            checked>
        <label class="form-check-label" for="inox">
            Acero Inox
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="material" id="carbon"
            value="Acero al carbon">
        <label class="form-check-label" for="carbon">
            Acero al Carbon
        </label>
    </div>

    <div class="form-check">
        <input class="form-check-input" type="radio" name="material" id="aluminio" value="aluminio">
        <label class="form-check-label" for="aluminio">
            Aluminio
        </label>
    </div>
    
    <div class="form-check">
        <input class="form-check-input" type="radio" name="material" id="nylamid" value="nylamid">
        <label class="form-check-label" for="nylamid">
            Nylamid
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="material" id="bronze" value="bronze">
        <label class="form-check-label" for="bronze">
            Bronze
        </label>
    </div>
    <div>
        <input type="hidden" name="opcion_seleccionada" value="">
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <input type="submit" id="agregar-cotizacion" class="btn btn-success" value="Registrar Partida">
    </div>
</form>

<!-- tabla -->

templates/index.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
  <h1 class="text-center">APLICACION PARA GENERAR PRESUPUESTOS</h1>
  <h2 class="text-center">INDUSTRIAL SHOP METALIC</h2>
</p>
{% endblock %}